version: '3.1'
services:
  nginx:
    container_name: docker-magento_nginx
    image: nginx:latest
    volumes:
     - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
     - ../web:/usr/share/nginx/www
    networks:
      project_net:
        ipv4_address: 172.22.0.102

  php:
    container_name: docker-magento_php
    build: 
      context: .
      dockerfile: ./php/Dockerfile  
    volumes:
     - ../web:/usr/share/nginx/www
    ports:
      - 9000
    networks:
      project_net:
        ipv4_address: 172.22.0.104

  db:
    container_name: docker-magento_mysql
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      project_net:
        ipv4_address: 172.22.0.108

  redis:
    container_name: docker-magento_redis
    image: redis
    ports:
      - 6379
    networks:
      project_net:
        ipv4_address: 172.22.0.109

  mail:
    container_name: docker-magento_mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      project_net:
        ipv4_address: 172.22.0.110

  adminer:
    container_name: docker-magento_adminer
    image: adminer
    restart: always
    ports:
      - 8222:8080
    networks:
      project_net:
        ipv4_address: 172.22.0.112

networks:
  project_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16