version: '3.1'
services:
  nginx:
    container_name: docker-magento_nginx
    image: nginx:latest
    volumes:
     - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx_conf/lojista.conf:/etc/nginx/conf.d/lojista.conf
     - ../web:/usr/share/nginx/www
    ports:
      - 80:80
      - 443:443
    expose:
      - 443
    links:
      - db
      - php:docker-magento_php
      - mail
      - redis
    depends_on:
      - php
    networks:
      project_net:
        ipv4_address: 172.22.0.102

  php:
    container_name: docker-magento_php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
     - ../web:/usr/share/nginx/www
    ports:
      - 9000:9000
    networks:
      project_net:
        ipv4_address: 172.22.0.104

  db:
    container_name: docker-magento_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
    ports:
      - 3306:3306
    networks:
      project_net:
        ipv4_address: 172.22.0.108

  redis:
    container_name: docker-magento_redis
    image: redis
    ports:
      - 6379:6379
    networks:
      project_net:
        ipv4_address: 172.22.0.109

  mail:
    container_name: docker-magento_mailhog
    image: mailhog/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./volumes/mailhog/volume:/maildir
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      project_net:
        ipv4_address: 172.22.0.110

  adminer:
    container_name: docker-magento_adminer
    image: adminer
    restart: always
    ports:
      - 8222:8080
    networks:
      project_net:
        ipv4_address: 172.22.0.112
    links:
      - db

networks:
  project_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16